os: linux
sudo: false
language: go

go:
  - 1.15.x
  - 1.16.x
  - master

matrix:
  allow_failures:
    - go: master

branches:
  only:
    - master
    - tiup

notifications:
  email:
    on_success: always
